name: upload my image to DockerHub

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build test image
        run: docker build --tag app:test .

      - name: Run container
        run: docker run -d --name app -p 80:3000 app:test

      - name: Set up Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Install Python deps for tests
        run: pip install requests webdriver_manager selenium pytest

      - name: Run PyTest
        run: pytest -rA

      - name: Cleanup
        if: always()
        run: |
          docker logs app || true
          docker rm -f app || true
