name: upload my image to DockerHub

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build
        run: |
          docker build . --tag ${{ secrets.DOCKER_USER }}/${{ secrets.PROJECT }}:latest

      - name: Push to DockerHub
        run: |
          docker push ${{ secrets.DOCKER_USER }}/${{ secrets.PROJECT }}:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy site
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          script_stop: true
          script: |
            set -euo pipefail
            cd /home/ubuntu/app
            if docker compose version >/dev/null 2>&1; then
              DC="docker compose"
            else
              DC="docker-compose"
            fi
            sudo $DC pull
            sudo $DC up -d --force-recreate
