name: upload my image to DockerHub

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build
        run: docker build --tag app .

      - name: Run Docker
        run: docker run -d --name app -p 80:3000 app

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Install software
        run: sudo apt-get install -y chromium-browser

      - name: Install the necessary packages
        run: pip install requests webdriver_manager selenium pytest

      - name: Run the PyTest script
        run: pytest -rA
