name: upload my image to DockerHub

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # ===== QA לפני בניית האימג' =====
      - name: Build test image
        run: docker build --tag app:test .

      - name: Run container for tests
        run: docker run -d --name app -p 80:3000 app:test

      - name: Set up Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Install Python deps for tests
        run: pip install requests webdriver_manager selenium pytest

      - name: Run PyTest
        run: pytest -rA

      - name: Cleanup test container
        if: always()
        run: |
          docker logs app || true
          docker rm -f app || true

      # ===== Build & Push =====
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build
        run: docker build . --tag ${{ secrets.DOCKER_USER }}/${{ secrets.PROJECT }}:latest

      - name: Push to DockerHub
        run: docker push ${{ secrets.DOCKER_USER }}/${{ secrets.PROJECT }}:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: deploy site
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          script_stop: true
          script: |
            cd /home/ubuntu/app
            sudo docker compose pull && sudo docker compose up -d --force-recreate
